name: CD

on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    uses: Seyrinian/.github/.github/workflows/build.yml@main
    with:
      is_build: true
  release:
    needs: build
    uses: Seyrinian/.github/.github/workflows/release.yml@main
    with:
      is_publish: false
      is_build: true
    secrets:
      SEMANTIC_BOT_APP_ID: ${{ secrets.SEMANTIC_BOT_APP_ID }}
      SEMANTIC_BOT_PRIVATE_KEY: ${{ secrets.SEMANTIC_BOT_PRIVATE_KEY }}
